### ISSUE TITLE
JOSS Review: Problematic e-use of code from  pboley/oifits

### ISSUE THREAD

**Issue by mwcraig** [shreyasbapat/python-oifits#2]
Hi @shreyasbapat, @arnavbhavsar and @ananyas2501,

I'm one of the reviewers for your submission to JOSS, https://github.com/openjournals/joss-reviews/issues/1743.

### *Roughly 90% of the code in this repository is taken directly from @pboley's `oifits` at https://github.com/pboley/oifits.* 

In several places some reformatting to be closer to PEP8 has been done, and the code has been updated to use `astropy.io.fits` instead of `pyfits` (though @pboley's code also uses `astropy.io.fits` if `pyfits` is not installed), and the high-level class structure is different. At the end of this issue I provide a few of examples of overlap.

There are a few problem with that:

1. From a software license point of view, @pboley removed the license from the code (it had been BSD 3-clause, I think?) in https://github.com/pboley/oifits/commit/550aca8018f187f7aee4a4ca6f0d5b952cf8df5c. That means (whether that was their intention or not) that you need their permission to reuse the code, and definitely need their permission to include their code in your code.
2. From the point of view of the paper, @pboley ought to be included as an author and arguably ought to be the primary author, given the extent of their code authorship.
3. In the event that @pboley permits use of the code after you request it but declines to be involved in the paper then you would need to much more prominently acknowledge his prior work in both each of the code files and in the paper.

There are a couple other things I'll address briefly in other issues.

### Examples of code re-use in `python-oifits` from `oifits`

I've included one example from each of the four files in the `python-oifits` source (excluding the tests). Each of those four files contains part of the file `oifits.py` in the `oifits` source:

1. In https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/data.py, compare the code starting at https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/data.py#L20 with the code at https://github.com/pboley/oifits/blob/master/oifits.py#L569
2. In https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/dataclasses.py, compare each of the class definitions with those in `oifits`, e.g. compare the definition of `OI_TARGET` in  https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/dataclasses.py#L14  to the definition of the same class in https://github.com/pboley/oifits/blob/master/oifits.py#L165. The same comparison can be done for `OI_WAVELENGTH`, `OI_VIS`, `OI_VIS2`, `OI_T3`, `OI_STATION`, and  `OI_ARRAY`.
3. In https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/read.py, compare the definition of `process` at https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/read.py#L39 to the definition of `open` in https://github.com/pboley/oifits/blob/master/oifits.py#L1285.
4. In https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/utils.py, compare the definition of `_plurals` at https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/utils.py#L6 with the definition of `_plurals` at https://github.com/pboley/oifits/blob/master/oifits.py#L93. The subsequent definitions of `_array_eq` and `_angpoint` are also essentially the same.

ping the editor, @arfon....

**Comment by shreyasbapat** [comment]
Right! I am sorry. I just noticed. I actually didn't know about this. I will rectify the issue ASAP.  
I included the copyright notice where I thought I was using the code. Sorry for this.

**Comment by shreyasbapat** [comment]
I actually first got @pboley 's code to work with latest python, then wrote my own classes instead, but somehow, I pushed the older code. I will understand what happened and update the repository ASAP. I included the copyright line in the `dataclasses` module, which was strictly the old code. I am sorry for all this mess. Maybe it's because of my negligence towards it. I am genuinely sorry for this type of mistake.

**Comment by shreyasbapat** [comment]
I understood what I did wrong. I am sorry. I created the same module in two different folders in my system, where in one I made this code work with my datasets, and then simply created a desired API (which I will want) and in the other one I created a different module by my API. And due to negligence, for which I am really sorry, I pushed the first one (Which I never intended to). And then overtime I never noticed as the APIs were exactly same, and Most of the methods were also same (Beacause I designed them so). 
I am really ashamed of this small mistake. I have taken down the code, and I will polish the other modules, test it and push it ASAP. Sorry for this @mwcraig

**Comment by mwcraig** [comment]
@shreyasbapat  -- mistakes happen, and the purpose of review is to catch them so that they can be fixed. I tried to keep my original comment as dispassionate as possible to allow the possibility for fixing the issue. I won't have time to come back around to this for a few more days (more likely next weekend), so there is time from my point of view.

**Comment by shreyasbapat** [comment]
Thanks a lot @mwcraig . This was really unintentional. I will fix this in time.

**Comment by pboley** [comment]
Well, I just saw the JOSS draft and review from @mwcraig.  Quickly opened the repo and saw more or less my python oifits module copied verbatim.  Perplexing.

**Comment by shreyasbapat** [comment]
Yes, true. I am sorry. Never intended to publish this. Sorry @pboley .

**Comment by shreyasbapat** [comment]
For the sake of the problem that occurred, I will remove the submission. I am again sorry @pboley . I will submit again with a proper submission

**Comment by pboley** [comment]
From what I can understand, you created a new module using the same API as an existing module.  

What was the motivation?

Yet you write this in the readme:
"oifits is a part of my Major Technical Project of my B.Tech. Degree. I faced the issue of not understanding exactly what the data was, and there was NO PYTHON MODULE which can tell me what's inside the data file. So I spent a significant amount of my research in understanding the data. And I don't want this to happen to anyone who wants to do their research using the world's largest telescope ;)"

Since you apparently wrote a second module, maybe you could just share the repo?

**Comment by shreyasbapat** [comment]
The motivation was to make the data easily readable for EHT related applications. 

The mistake I made was, I used one of your 2013 codes to read the data, but then realised that I wanted the API to be different and easy for my usecase. 

I rewrote the code. And I pushed the alpha version I created using your 2013 code (This was by mistake.) I was planning to use your DataClasses where I wrote the copyright notice from your licence. https://github.com/shreyasbapat/python-oifits/blob/master/src/oifits/dataclasses.py#L3 
But as all of the code was messed up, it makes actually no sense. I understand the concerns. I have removed the code as soon as I realised. I am really sorry. I will share the code once I make that available online. But due to some exams, I won't be able to do that right now. 

Meanwhile https://github.com/openjournals/joss-reviews/issues/1743#issuecomment-533917310 
I have asked to remove the submission. I am sorry once again. This was negligence in my part and I had no intent to do so. (Otherwise there was no actual meaning of including your copyright notice in one of the modules) . I am sorry for all the trouble caused.

**Comment by shreyasbapat** [comment]
I will also remove all the code from the history of git. As it is unjust to have that otherwise. I am very sorry on this part, I realise this is a mistake. I seek your apology for the same. And I hope you will forgive me for this @pboley .

**Comment by shreyasbapat** [comment]
Since I cleaned the history, links won't open. 
Here is how the dataclass.py header looked:
```
"""
These Classes are inspired by Paul Boley's code for OIFITS Data!
Copyright (c) 2013, Paul Boley
Copyright (c) 2019, Shreyas Bapat
"""

I can definitely not justify this, but this was really unintentional. 
```

**Comment by shreyasbapat** [comment]
I  have made the code private to https://github.com/shreyasbapat/bad-oifits
It was a wrong push that i made, and I have removed all those file from this repo. Please ask me the rights to view the private repository, in order to understand what actually happened.
